apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: default
  labels:
    app: web
    creador: elmerreal
spec:
  containers:
  - name: container-nginx
    image: nginx
    ports:
    - containerPort: 80