apiVersion: v1
kind: Service
metadata:
  name: service-postgres
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: service-adminer
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - port: 8080
      targetPort: 8080