apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-nginx-replicaset
  labels:
    creador: elmerreal
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - name: container-nginx
        image: nginx

